### ISSUE TITLE
Support lights

### ISSUE THREAD

**Issue by sirpalee** [LumaPictures/usd-arnold#16]
Support all the compatible HdLight types.

**Comment by chadrik** [comment]
How do we deal with all the custom ai attributes?

**Comment by sirpalee** [comment]
There isn't really a clean way to do that for now. Since we are not interacting with the USD scene directly, we can't access those attributes directly in the render delegate's light prims. After taking a quick look at the adapters / HD prims, I think primvars will be passed along for sprims (ie lights). So moving the ai attributes to the primvar scope (constant scope) could give us a way to access custom attributes. The same problem applies to polymeshes as well.

**Comment by sirpalee** [comment]
Added initial light support, including texturing for rect and dome lights.
