### ISSUE TITLE
Updating the UsdMaya shader exporter to work with the latest MtoA builds

### ISSUE THREAD

**Issue by sirpalee** [LumaPictures/usd-arnold#18]
We fallen behind on MtoA support as we still rely on headers and functions that are not exposed in MtoA 3 anymore.

**Comment by chadrik** [comment]
We won't need mtoa headers if we move to an Sdr-based approach, correct?

**Comment by sirpalee** [comment]
Correct. Ideally, we would want to have access to MtoA's logic in some way (exposed interfaces), since there are exceptions for shader translation that can't be done through Sdr registry. (ie, a 1:1 parameter mapping based translation)

**Comment by sirpalee** [comment]
This is done. Now we rely on the new functions exposed in newer mtoa versions. The advantage of this approach, we don't need to link against mtoa anymore.
