### ISSUE TITLE
render delegate: UsdPreviewSurface materials not translated

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/usd-arnold#29]
- Load the attached usda
- Turn on materials
- Should show up fine in HdStream
- Switch to arnold render delegate
- No materials

[cube_texture.usda.zip](https://github.com/LumaPictures/usd-arnold/files/2747938/cube_texture.usda.zip)

**Comment by sirpalee** [comment]
Fixed the second issue, and a third one I just found. HdAiSetParameter only translated TfToken parameters to AtString and didn't support SdfAssetPath ones.

After fixing these two (and changing the terminal to outputs:surface) the example file renders as expected. (except no support for default lights)
