### ISSUE TITLE
Does it support only USD-Arnold MtoA1.4?

### ISSUE THREAD

**Issue by gshankar165** [LumaPictures/usd-arnold#36]
Modules
Current
*We support MtoA-1.2 and MtoA-1.4.*
Does this mean that code support only  MtoA-1.2 and MtoA-1.4.Because Maya comes with 3.2 now. is the code old or has been updated now?
Can you please help me to understand?

**Comment by sirpalee** [comment]
Hi!

No, the readme was simply not updated for a while. The usdMaya plugin works with any of the newer mtoas, as it is not using the c++ api anymore to trigger translation of a shader.
